package com.maisonbonheur.perfumebackend.entity.enums;

public enum Intensity {
    LIGHT, MEDIUM, STRONG, FRESH
}

enum Season {
    SPRING, SUMMER, AUTUMN, WINTER, ALL, NIGHT
}

enum Mood {
    ROMANTIC, FRESH, ELEGANT, PLAYFUL, INTENSE, DARING, MYSTERIOUS, 
    EXOTIC, MAJESTIC, SENSUAL, WARM, SPIRITUAL, JOYFUL, ENERGETIC, 
    REFRESHING, CALM, SERENE, CRISP, LUXURIOUS, REGAL, COMFORTING, 
    DEEP, NOSTALGIC, PURE, TRANQUIL, SOPHISTICATED
}

public enum OrderStatus {
    PENDING, PROCESSING, SHIPPED, DELIVERED, CANCELLED
}